#include <fstream>
#include <iostream>
#include <memory>
#include <string>
#include <regex>
#include <array>
#include <vector>
#include <queue>
#include <utility>
#include <tuple>
#include <map>
#include <semaphore.h>